[settings]
dark_absolute_threshold: 0.0001
discarded_edge_size: 50
mask_min_structure_size: 0
mask_structure_growth: 0
min_cost_change = 1e-4
;e, p[n]
model_type = p3
background_percentile = 10.0
print_pixelmath_expression = true
show_debug_pictures = true

e_inital_significant_gradient_min_percentile = 5.0
e_inital_amplitude_clip_percentile_min = 40
e_inital_amplitude_clip_percentile_max = 60
;linear, soft_l1
e_loss_function = linear
e_method = trf
e_ftol = 1e-5
